apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: castroclucas82/portal-noticias
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap